Repository Tenkaklet/coderdojo, pull requests merged in 2022-04, with the labels that each got.

#42 Test av PR
  backend/app/libraries/pquery/plugins/mail/mail.php
Labels: good first issue

#43 added database
  backend/coderdojo.sql
Labels: enhancement

#44 added logo to frontend
  frontend/src/img/logo.png
Labels: enhancement

#45 Feature/navbar
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.js
  frontend/src/components/App.css
  frontend/src/components/App.js
  frontend/src/components/Navbar.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/tailwind.config.js
Labels: enhancement, good first issue

#46 navbar finished without functionality
  frontend/package.json
  frontend/src/components/Navbar.js
Labels: enhancement

#47 bug fix
  frontend/src/components/Navbar.js
Labels: bug

#48 added title and favicon
  frontend/public/favicon.ico
  frontend/public/index.html
Labels: enhancement

#50 fixed bugs
  backend/app/controllers/aboutController.php
  backend/app/helpers/publicFunctions.php
  backend/app/libraries/pquery/plugins/dbconnect/dbconf.php
  backend/app/libraries/pquery/plugins/dbconnect/dbconnect.php
  backend/app/models/About.model.php
  backend/app/require.php
  backend/app/views/about/get.view.php
Labels: bug

#51 added slideshow
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Navbar.js
  frontend/src/components/Slideshow.js
  frontend/src/img/code-kid.jpg
  frontend/src/index.css
Labels: enhancement

#55 navbar redesign
  frontend/src/components/Navbar.js
  frontend/src/index.css
Labels: enhancement

#57 Header almost finished
  frontend/src/App.js
  frontend/src/components/Header.js
  frontend/src/components/Navbar.js
  frontend/src/components/Volunteer.js
  frontend/src/index.css
Labels: enhancement

#58 bug fix
  frontend/src/components/Volunteer.js
  frontend/src/index.css
Labels: enhancement

#60 volunteer structure finished
  frontend/src/components/Volunteer.js
  frontend/src/img/vol.jpg
  frontend/src/img/vol1.jpg
  frontend/src/index.css
Labels: enhancement
